/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as AuthenticatedTimetableRouteImport } from "./routes/_authenticated/timetable"
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings"
import { Route as AuthenticatedNotificationsRouteImport } from "./routes/_authenticated/notifications"
import { Route as AuthenticatedMarksRouteImport } from "./routes/_authenticated/marks"
import { Route as AuthenticatedCoursesRouteImport } from "./routes/_authenticated/courses"
import { Route as AuthenticatedAttendanceRouteImport } from "./routes/_authenticated/attendance"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: "/timetable",
  path: "/timetable",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: "/marks",
  path: "/marks",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: "/courses",
  path: "/courses",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: "/attendance",
  path: "/attendance",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute
  "/login": typeof AuthLoginRoute
  "/attendance": typeof AuthenticatedAttendanceRoute
  "/courses": typeof AuthenticatedCoursesRoute
  "/marks": typeof AuthenticatedMarksRoute
  "/notifications": typeof AuthenticatedNotificationsRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/timetable": typeof AuthenticatedTimetableRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedIndexRoute
  "/login": typeof AuthLoginRoute
  "/attendance": typeof AuthenticatedAttendanceRoute
  "/courses": typeof AuthenticatedCoursesRoute
  "/marks": typeof AuthenticatedMarksRoute
  "/notifications": typeof AuthenticatedNotificationsRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/timetable": typeof AuthenticatedTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_authenticated/attendance": typeof AuthenticatedAttendanceRoute
  "/_authenticated/courses": typeof AuthenticatedCoursesRoute
  "/_authenticated/marks": typeof AuthenticatedMarksRoute
  "/_authenticated/notifications": typeof AuthenticatedNotificationsRoute
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute
  "/_authenticated/timetable": typeof AuthenticatedTimetableRoute
  "/_authenticated/": typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/attendance"
    | "/courses"
    | "/marks"
    | "/notifications"
    | "/settings"
    | "/timetable"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/attendance"
    | "/courses"
    | "/marks"
    | "/notifications"
    | "/settings"
    | "/timetable"
  id:
    | "__root__"
    | "/_auth"
    | "/_authenticated"
    | "/_auth/login"
    | "/_authenticated/attendance"
    | "/_authenticated/courses"
    | "/_authenticated/marks"
    | "/_authenticated/notifications"
    | "/_authenticated/settings"
    | "/_authenticated/timetable"
    | "/_authenticated/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/timetable": {
      id: "/_authenticated/timetable"
      path: "/timetable"
      fullPath: "/timetable"
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/settings": {
      id: "/_authenticated/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/notifications": {
      id: "/_authenticated/notifications"
      path: "/notifications"
      fullPath: "/notifications"
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/marks": {
      id: "/_authenticated/marks"
      path: "/marks"
      fullPath: "/marks"
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/courses": {
      id: "/_authenticated/courses"
      path: "/courses"
      fullPath: "/courses"
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/attendance": {
      id: "/_authenticated/attendance"
      path: "/attendance"
      fullPath: "/attendance"
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
